%: %.c lib/stringInput.c
	gcc.exe -Wall -o % %.c lib/stringInput.c

hashingSeparateChaining: hashingSeparateChaining.c lib/stringInput.c
	gcc.exe -Wall -o hashingSeparateChaining hashingSeparateChaining.c lib/stringInput.c

h: hashingFromScratch.c lib/stringInput.c
	gcc.exe -Wall -o hashingFromScratch hashingFromScratch.c lib/stringInput.c

